#!/bin/bash
# ===================================================================================
# | WordPress Auto Konfiguration
# ===================================================================================

# Suchmaschinen die Indexierung verbieten.
wp option update blog_public 0

# WordPress komplett updaten
wp cli update
wp core update
wp plugin update --all
wp theme update --all

# Sprache ändern
wp language core install --activate de_DE

# Datum und Zeit anpassen
wp option update date_format 'Y-m-d'
wp option update time_format 'H:i'
wp option update start_of_week 1
wp option update timezone_string 'Europe/Zurich'

# Link Struktur setzten
wp rewrite structure '/%post_id%/%postname%' --category-base='/kat/' --tag-base='/tag/'
wp rewrite flush

# Jahr / Monat Ordner Struktur deaktivieren
wp option update uploads_use_yearmonth_folders 0

# Kommentare per Standart deaktiviert
wp option set default_comment_status closed;

# Ping per Standart deaktiviert
wp option set default_ping_status closed;

# Blog Name und Beschreibung mit vorübergehendem Inhalt füllen
wp option update blogname "PageSpeed+"
wp option update blogdescription "Professional Performance"
# wp option update admin_email someone@example.com
# wp option update default_role author

# Standart Müll entfernen
wp plugin uninstall akismet hello
wp theme uninstall twentyfifteen twentysixteen
wp post delete $(wp post list --post_type='page' --format=ids)
wp post delete 1 --force
wp comment delete 1 --force
wp widget delete $(wp widget list sidebar-1 --format=ids);

wp plugin install code-snippets optimus query-monitor snitch autodescription updraftplus vevida-optimizer ninjafirewall
# wp plugin install disqus-conditional-load elasticpress search-by-algolia-instant-relevant-results responsify-wp favicon-by-realfavicongenerator worker lazy-load-for-comments p3-profiler pods searchwp-api secsign table-of-contents-plus tablepress the-events-calendar wp-ultimate-csv-importer wp-external-links wp-sweep

# Kommentare und Pingbacks deaktivieren
# wp post list --format=ids | xargs wp post update --comment_status=closed
# wp post list --format=ids | xargs wp post update --ping_status=closed
